version: "3.9"

services:
  mariadb:
    image: mariadb:11.5.2
    container_name: mariadb-11.5
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: mysql
      MARIADB_DATABASE: fineract_tenants
      MARIADB_USER: fineract
      MARIADB_PASSWORD: fineract
    volumes:
      - mariadb-data:/var/lib/mysql

  fineract:
    image: apache/fineract:latest
    container_name: fineract
    depends_on:
      - mariadb
    restart: unless-stopped
    ports:
      - "8443:8443"
    environment:
      FINERACT_HIKARI_JDBC_URL: jdbc:mariadb://mariadb:3306/fineract_tenants?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      FINERACT_HIKARI_USERNAME: fineract
      FINERACT_HIKARI_PASSWORD: fineract
      JAVA_TOOL_OPTIONS: "-Duser.timezone=UTC"

volumes:
  mariadb-data:
